services:
  nginx:
    depends_on:
      - nuxt_app
    image: nginx:latest
    ports:
      - "8081:80"
    expose:
      - "8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    restart: always

  nuxt_app:
    build: .
    restart: always
